### ISSUE TITLE
NoneType' object has no attribute 'group'

### ISSUE THREAD

**Issue by Abhimanyudev7** [Enderness/Justdial-Scraper#1]
shows error  'NoneType' object has no attribute 'group' on execute button

**Comment by 3nd3r1** [comment]
Hello!

What query and location where you using to get this error?

**Comment by Abhimanyudev7** [comment]
I'm using Mumbai as location and medical as keyword

**Comment by 3nd3r1** [comment]
It probably had something to do with phone numbers. I fixed a lot of bugs in yesterday's commit. Try to download the latest code and tell me if the error remains.

**Comment by Abhimanyudev7** [comment]
Yes, I check the latest version. 

![image](https://user-images.githubusercontent.com/20383603/82077679-71e5cf80-96fd-11ea-88e1-d3255ea04e75.png)

As I'm a newbie or else I would have debugged it and tried to solve this.

**Comment by 3nd3r1** [comment]
Interesting.. Could you open the app again and click yes on the update then tell me whats in the console when the error occurs.

**Comment by Abhimanyudev7** [comment]
After clicking on yes on update it just gets close

**Comment by 3nd3r1** [comment]
If you reopen?

**Comment by Abhimanyudev7** [comment]
then it again asks for update

**Comment by 3nd3r1** [comment]
try to update now and reopen

**Comment by Abhimanyudev7** [comment]
Checked nothing is happening in the grid view. No record

**Comment by 3nd3r1** [comment]
Yes but what does the console output

**Comment by Abhimanyudev7** [comment]
No output.

**Comment by 3nd3r1** [comment]
So no more errors. That's great!

**Comment by Abhimanyudev7** [comment]
yes but it still doesn't show data in the grid.

**Comment by 3nd3r1** [comment]
Sir I finally was able to recreate this issue and fixed it.

**Comment by Abhimanyudev7** [comment]
Great It's Working
